import enum

class ChargeMode(enum.Enum):
    UNKNOWN = 0
    QC2_0 = 1
    QC3_0 = 2


class Screen(enum.Enum):
    MEASUREMENT_MAIN_INTERFACE = 0
    QUICK_CHARGE_RECOGNITION_INTERFACE = 1
    DATA_RECORDING_INTERFACE = 2
    WIRE_IMPEDANCE_MEASUREMENT_INTERFACE = 3
    VOLTAGE_GRAPHING_INTERFACE = 4
    CURRENT_GRAPHING_INTERFACE = 5
    SETTINGS_INTERFACE = 6



